"""initial

Revision ID: f56caa332d96
Revises:
Create Date: 2026-04-22 16:27:04.239911

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f56caa332d96"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cached_movies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kinopoisk_id", sa.Integer(), nullable=False),
        sa.Column("name_ru", sa.String(length=500), nullable=True),
        sa.Column("name_en", sa.String(length=500), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("rating", sa.String(length=20), nullable=True),
        sa.Column("genres_json", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("poster_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "cached_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cached_movies_kinopoisk_id"),
        "cached_movies",
        ["kinopoisk_id"],
        unique=True,
    )
    op.create_table(
        "saved_movies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("kinopoisk_id", sa.Integer(), nullable=False),
        sa.Column(
            "saved_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "kinopoisk_id", name="uq_user_movie"),
    )
    op.create_index(
        op.f("ix_saved_movies_user_id"), "saved_movies", ["user_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_activity",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_saved_movies_user_id"), table_name="saved_movies")
    op.drop_table("saved_movies")
    op.drop_index(op.f("ix_cached_movies_kinopoisk_id"), table_name="cached_movies")
    op.drop_table("cached_movies")
    # ### end Alembic commands ###
